GET http://localhost:3000/doorDashRoute/

###

GET http://localhost:3000/doorDashRoute/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImRkLXZlciI6IkRELUpXVC1WMSJ9.eyJhdWQiOiJkb29yZGFzaCIsImlzcyI6IjRmMjVjZTA5LTI4YWUtNGViMS1hNjczLWYwMjgyZjRlYTdhMyIsImtpZCI6ImE0ZTczMDBhLWNlM2EtNDljOC04ZjYxLWQ1NGYxYzg4MjIwNCIsImV4cCI6MTcwNzUzMDUzNSwiaWF0IjoxNzA3NTMwMjM1fQ.PQWcqf6MK26T6S-Ia3UEbBkYvgQ4kWKaMZKZqX_6-yc

###
