GET http://localhost:3000/products


###
GET http://localhost:3000/products/prod

###
GET http://localhost:3000/products/id/130

###
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "ProductName": "ProductNameTest 51",
    "Description": "DescriptionTESt",
    "VendorID": 3,
    "Price": 10,
    "CategoryID": 1,
    "StockQuantity": 5
}
###

POST http://localhost:3000/products
Content-Type: application/json

{
    "ProductName": "ProductNameTest 51",
    "Description": "DescriptionTESt",
    "VendorID": 3,
    "Price": 10,
    "CategoryID": 1,
    "StockQuantity": 5
}

###

DELETE http://localhost:3000/products/5